config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cmv.core:
      branch: main
      repo: https://github.com/cessda/cessda.cmv.core
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-sapphire-mammoth.sh
        container: qc.acc_sunny-corn-quetzal
  QC.Doc:
    repos:
      github.com/cessda/cessda.cmv.core find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-buff-kudu.sh
        container: qc.doc_sickly-cream-macaw
      github.com/cessda/cessda.cmv.core git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-white-centipede.sh
        container: qc.doc_cheeky-pumpkin-indri
      github.com/cessda/cessda.cmv.core markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cinnabar-vole.sh
        container: qc.doc_blurry-wisteria-cuscus
  QC.Lic:
    repos:
      github.com/cessda/cessda.cmv.core licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-gharial.sh
        container: qc.lic_randy-silver-meerkat
  QC.Met:
    repos:
      github.com/cessda/cessda.cmv.core cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-charcoal-salamander.sh
        container: qc.met_crappy-rose-russel
  QC.Sty:
    repos:
      github.com/cessda/cessda.cmv.core checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-bistre-axolotl.sh
        container: qc.sty_queasy-cornflower-flamingo
      github.com/cessda/cessda.cmv.core jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-razzmatazz-russel.sh
        container: qc.sty_crabby-sangria-zebra
  QC.Ver:
    repos:
      github.com/cessda/cessda.cmv.core get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-bistre-peccary.sh
        container: qc.ver_craggy-mustard-ibis
timeout: 5400
